name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: netfixhub_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Test and Deploy
      run: |
        # Tus pasos de test
        echo "Running tests..."
        
        # Si los tests pasan, desplegar
        if [ $? -eq 0 ]; then
          echo "Tests passed, deploying..."
        else
          echo "Tests failed!"
          exit 1
        fi
